webapp:
    build: .
    dockerfile: Dockerfile-development
    ports:
        - "5000:5000"
    links:
        - mongodb
    volumes:
        - .:/usr/src/app/
        - /usr/src/app/node_modules
    environment:
        NODE_ENV: development
        MONGODB_URI: mongodb://mongodb:27017/mern-template

mongodb:
    image: mongo:latest
    restart: always
    ports:
        - "27017:27017"
